### ISSUE TITLE
c-step not showing check mark

### ISSUE THREAD

**Issue by emm1R** [CSCfi/csc-ui#73]
<img width="495" alt="Screenshot 2023-01-09 at 18 17 49" src="https://user-images.githubusercontent.com/20052903/211355673-a4dd09c0-5513-4ef1-9839-6a089846944c.png">

I guess the recent commit for c-steps broke something? The check mark is not visible (using Safari 16.0).

**Comment by razorfever** [comment]
Fixed in #174
