### ISSUE TITLE
Release changes

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/csc-ui#78]
It would be nice to know what changes are coming with the releases. 

We can see there's a new version in NPM, but there's no matching tag on github, and nothing we can read (except the code) to know if the changes impact our code in any way, or which new features are available that we could take into use.

NPM says there's 1300+ downloads per week, so it seems like there are enough people using this library that it would be useful to many.

**Comment by csc-felipe** [comment]
Right now, I can see a commit with `bump version to 0.6.7`, and that's the latest version I would expect to be available, but npm has version `0.6.12`. I feel confused.

**Comment by razorfever** [comment]
We have set up an automated changelog / releases creation now. Hopefully it makes things more clear in the future.
